### ISSUE TITLE
The display size increases, the content stays on the left.

### ISSUE THREAD

**Issue by oybek94** [vayvoo/intro-compoonent#1]
When I checked the display width to 1920px, the basic data went to the left. To correct this,  `justify-content: center;` need to do.
![Безымянный](https://user-images.githubusercontent.com/21256066/111952907-aab5b880-8b07-11eb-9116-411c30ae4693.jpg)

https://github.com/vayvoo/intro-compoonent/blob/ed561ccd10569234c19984fe5406d4e55214c50e/css/style.css#L13

**Comment by vayvoo** [comment]
thank you! issue is fixed
